### ISSUE TITLE
libusb-usbdk issue when installing usbdk twice

### ISSUE THREAD

**Issue by matlo** [daynix/UsbDk#1]
The libusb-usbdk returns the following error after installing usbdk twice:
Driver file operation error. Failed to open device symlink \\.\UsbDk (Failed to get error description for error code: 0x2)

**Comment by dmitryfleytman** [comment]
Thanks for the report.
We will investigate.

**Comment by dmitryfleytman** [comment]
Fixed at 458ad0f9a6a0a4993fb5d7cc404315c01d5f66b0

**Comment by matlo** [comment]
Thanks! I'll try to investigate on the other issue this evening.
