### ISSUE TITLE
Support for 0 byte bulk/interrupt transfers

### ISSUE THREAD

**Issue by msbroadf** [daynix/UsbDk#11]
Some devices use zero length bulk transfers, E.g iLok. 

 At the moment when passing a zero length transfer to the UsbDkHelper Read/WritePipe it will cause an STATUS_INVALID_USER_BUFFER error when it attempts to lock a zero length buffer in RedirectorStrategy (Line 248) and it then basically corrupts the internal state somewhere and causes the userspace program to crash.

**Comment by dmitryfleytman** [comment]
Thanks for the great bug report! Will be fixed in the next version.

**Comment by dmitryfleytman** [comment]
Fixed at 900b148f0a8a353a4a90f64e2f64e2696bcda103
