### ISSUE TITLE
UsbDK Installation failing- There is a problem with this Windows Installer package etc

### ISSUE THREAD

**Issue by lgexalter** [daynix/UsbDk#116]
When trying to install UsbDK in Windows 10 I am getting this erorr: **There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.**
![usbdk](https://user-images.githubusercontent.com/77845390/212184714-407c8c63-4005-4f49-ad05-5f7fd96d0621.PNG)

I previously had UsbDK installed and after uninstalling I am getting this error. I tried redownloading the installer, running as admin, from elevated Command Prompt, and in safe mode. [Here ](https://drive.google.com/file/d/1XXeZjqJu9WjR_ujjHtqaow-YXbhVagaI/view?usp=drivesdk) are my logs

**Comment by lgexalter** [comment]
I am getting this from Windows Event Viewer. `Product: UsbDk Runtime Libraries -- Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action InstallDriver, location: C:\Program Files\UsbDk Runtime Library\, command: C:\Program Files\UsbDk Runtime Library\\UsbDkInstHelper.exe i `
It seems like the issue is with UsbDkInstHelper.exe
Still can't figure out exactly what the issue is though...
I am also getting this warning from BTHUSB every time I try to install. Not sure if it's related. `The local adapter does not support an important Low Energy controller state to support peripheral mode.  The minimum required supported state mask is 0x2491f7fffff, got 0xffffffff.  Low Energy peripheral role functionality will not be available.`

**Comment by ybendito** [comment]
Please try following:
Unpack the MSI to some subdirectory, like this
cd c:\users\user\downloads
mkdir 122
msiexec /a UsbDk_1.0.22_x64.msi /qb TARGETDIR=%cd%\122
open administrator command line
go to the directory where the usbdkcontroller.exe is placed:
cd c:\users\user\downloads\122\USB Runtime Library etc
usbdkcontroller.exe -i

It will try to install the USBDK driver.
To uninstall it you can use 
usbdkcontroller.exe -u (also from the admin command line)

**Comment by lgexalter** [comment]
@ybendito 
Thanks for the reply.
Assuming you meant msiexec /a UsbDk_1.0.22_x64.msi /qb TARGETDIR=%cd%\122

I followed the instructions but it still failed.
```
Installing UsbDk driver
UsbDk driver installation failed
```

**Comment by ybendito** [comment]
@lgexalter 
I suggest to download
https://learn.microsoft.com/en-us/sysinternals/downloads/debugview
Run it (as an admin) before "usbdkcontroller -i", select "Capture->Win32 and Global Win32", then run "usbdkcontroller -i"
In case of error there should be some debugging output visible in DebugView

**Comment by lgexalter** [comment]
@ybendito 
```
00000001	0.00000000	[2264] UsbDkInstaller exception: CopyFile from C:\Users\Shani\Documents\122\UsbDk Runtime Library\UsbDk Runtime Library\UsbDk.sys to C:\Windows\System32\Drivers\UsbDk.sys failed. (The file exists.  Error code = 80)
```
Tried deleting and getting file in use error. But at least now I know what the error is.
Thanks!

**Comment by ybendito** [comment]
Try "Usbdkcontroller.exe -u", then reboot, then "Usbdkcontroller.exe -i"

**Comment by lgexalter** [comment]
@ybendito 
It worked! Thanks!!!
