### ISSUE TITLE
usbdk install failled on Windows 7 sp1 x64

### ISSUE THREAD

**Issue by inj30ct** [daynix/UsbDk#132]
usbdk install failled on Windows 7 sp1 x64 
When running the setup i get this error message

There is a problem with this Windows Installer package. A program run as part of the set up did not finish as expected. Contact your support personnel or package vendor

I have tried with the manual installation method 
Installation failled

Any fix for this issue

Thnx in advance.

**Comment by YanVugenfirer** [comment]
Please install the below KB and try again:
https://support.microsoft.com/en-us/topic/2019-sha-2-code-signing-support-requirement-for-windows-and-wsus-64d1c82d-31ee-c273-3930-69a4cde8e64f

**Comment by inj30ct** [comment]
> Please install the below KB and try again: https://support.microsoft.com/en-us/topic/2019-sha-2-code-signing-support-requirement-for-windows-and-wsus-64d1c82d-31ee-c273-3930-69a4cde8e64f

After install the kb update, the problem still exist
Any other fix for this issue

**Comment by YanVugenfirer** [comment]
Please provide the logs mentioned in https://github.com/daynix/UsbDk/wiki/Troubleshooting-UsbDk-installation

**Comment by inj30ct** [comment]
> Please provide the logs mentioned in https://github.com/daynix/UsbDk/wiki/Troubleshooting-UsbDk-installation

Problem just solved with this.
Manualy install the Kernel-Mode Driver Framework update for windows 7
The integrated one on the usbdk installer didn't succesfully installed, 
so the whole installation will stop.
Thanks for your attentions.
i hope this usefull for someone.

**Comment by YanVugenfirer** [comment]
Thanks for the update!
