### ISSUE TITLE
Uninstalling and reinstalling usbdk causes random BSODs

### ISSUE THREAD

**Issue by matlo** [daynix/UsbDk#2]
Uninstalling and reinstalling USBDK  causes random BSODs:
![img_2036](https://cloud.githubusercontent.com/assets/3289527/8023280/302c7ed6-0d05-11e5-825c-87a08dc5f9a1.JPG)
I wasn't able to get a kernel memory dump: the MEMORY.DMP file is not written to the disk (I still think I configured it right). I tried to find a method to reproduce the problem, and I ended up running the following bash script in a msys2 shell:
```
#!/bin/bash

export MSYS2_ARG_CONV_EXCL="*"
while :
do
  msiexec /x {DE78E7B1-43E5-4278-9678-174A6EC4444E} /qn
  msiexec /i UsbDk_1.0.4_x64.msi /qn
done
```
It generates a BSOD in about 5 minutes. Opening the device and printers panel may speed up the crash. I have many devices (more than 10) connected to my computer.

**Comment by dmitryfleytman** [comment]
Thanks for the report, we will investigate.
In case you get a crash dump on your system - please share with us.

**Comment by dmitryfleytman** [comment]
What is you Windows version?

**Comment by dmitryfleytman** [comment]
I tried on Windows 7 and 8 and didn't succeed to reproduce. Probably an interoperability issue with some specific device driver.

Could you please try to obtain kernel memory dump?

Thanks,
Dmitry

**Comment by matlo** [comment]
I'm using Windows 7 x64. I'll try again to get a kernel memory dump.

**Comment by dmitryfleytman** [comment]
Thanks!

**Comment by matlo** [comment]
Unfortunately I wasn't able to get a kernel memory dump. I think I configured it right, the BSOD even tells the memory is dumped to the disk, but I can't find any memory dump after rebooting.
However I observed that when the USB 3.0 host controller (ASMedia XHCI Controller 1042) is disabled, there's no BSOD...

**Comment by matlo** [comment]
I forgot to say the following points:
* I unplugged all devices from all USB busses before launching the crash test, so I'm pretty sure that the issue is due to my USB 3.0 host controller.
* I tried on another computer running Windows 7 x86, and the issue did not happen.

**Comment by dmitryfleytman** [comment]
There are a few factors that may prevent Windows from saving crash dumps or make Windows delete crash dumps on reboot.

Please check those links:
http://www.resplendence.com/whocrashed_dumpnotwritten
http://blogs.msdn.com/b/wer/archive/2009/02/09/kernel-dump-storage-and-clean-up-behavior-in-windows-7.aspx

There is no real reason for Windows to fail save crash dumps on Usb stack crashes...

**Comment by YanVugenfirer** [comment]
Hi,

Please check pages 30-34:
http://www.slideshare.net/YanVugenfirer/windows-guestdebugging-kvmforum2012

Best regards,
Yan.

On Wed, Jun 24, 2015 at 7:58 PM, Dmitry Fleytman <notifications@github.com>
wrote:

> There are a few factors that may prevent Windows from saving crash dumps
> or make Windows delete crash dumps on reboot.
>
> Please check those links:
> http://www.resplendence.com/whocrashed_dumpnotwritten
>
> http://blogs.msdn.com/b/wer/archive/2009/02/09/kernel-dump-storage-and-clean-up-behavior-in-windows-7.aspx
>
> There is no real reason for Windows to fail save crash dumps on Usb stack
> crashes...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/daynix/UsbDk/issues/2#issuecomment-114941552>.
>



-- 
-----------------------------------------------------------------------
Daynix Computing LTD
Yan Vugenfirer, CEO
Email: yan@daynix.com
Phone (Israel): +972-54-4758084
Phone (USA): +1-7204776716
Phone (UK): +44-2070482938
Web: www.daynix.com

**Comment by matlo** [comment]
This is my crash dump configuration:
![dump](https://cloud.githubusercontent.com/assets/3289527/8339949/88809c7a-1abb-11e5-9211-850ef9c67285.png)
![crashcontrol](https://cloud.githubusercontent.com/assets/3289527/8339950/88810cf0-1abb-11e5-82d6-ab3cf2bc4c9e.png)
And my pagefile configuration:
![pagefile](https://cloud.githubusercontent.com/assets/3289527/8339948/8880335c-1abb-11e5-9807-41fc07a8b600.png)
(my RAM is 8192MB)

**Comment by matlo** [comment]
I forgot to say that I have 44GB of free space on my system drive.

**Comment by dmitryfleytman** [comment]
This is strange.

When you reboot your system after the crash and login to Windows, does is show a window with notification about system restart due to unrecoverable problem and proposition to send problem report to Microsoft?

Could you check whether crash dump present in c:\Windows\ in case you DO NOT CLOSE that Window?
Sometimes Windows deletes the crash dump when this window is closed.

In case there is no crash dump in any case, could you please check whether there are minidumps? Please post those if any.

Thanks,
Dmitry

**Comment by matlo** [comment]
Hi Dmitry,
I don't get this window after rebooting. I'll see if I can get a minidump.
This morning I wasn't able to get the BSOD, that's strange.
I'm thinking about reinstalling Windows...

**Comment by dmitryfleytman** [comment]
Please also check whether there are driver updates for ASMedia XHCI Controller, I see there are a few BSOD reports related to their driver.

**Comment by dmitryfleytman** [comment]
Hi @matlo, do you still see this problem?

**Comment by matlo** [comment]
Hi,
I reinstalled Windows and updated the drivers, and I don't have this problem anymore.
