### ISSUE TITLE
I can't install UsbDk_1.0.12_x64.msi again!

### ISSUE THREAD

**Issue by jiaojialulu** [daynix/UsbDk#22]
Hi
At first ,I uninstall UsbDk_1.0.12_x64.msi.
And then I want to use it again, but there is a warning like this:
![image](https://cloud.githubusercontent.com/assets/14901098/13554416/4db05072-e3e2-11e5-88fc-d268d4c79aa6.png)
what should I do now?

**Comment by dmitryfleytman** [comment]
Hi,

Thanks for the report.

Please try to do the same manually without MSI to see what is the problem.
Having UsbDk installed, run from UsbDk installation folder (c:\program files\UsbDk runtime libraries):
1. "UsbDkController.exe -u"
2. "UsbDkController -i"

Thanks,
Dmitry

**Comment by jiaojialulu** [comment]
I can't install UsbDk,so I don't have this folder.

**Comment by dmitryfleytman** [comment]
Oh, I see.
Could you check if you have files UsbDk.sys or UsbDkHelper.dll somewhere on the disk?

**Comment by jiaojialulu** [comment]
I restart my computer some times, now it's OK!!!

**Comment by lz2004xxw** [comment]
> I restart my computer some times, now it's OK!!!
> thanks !!!

how did u fixed it? i met the same problem
