### ISSUE TITLE
redirect usb device timeout

### ISSUE THREAD

**Issue by jinyyu** [daynix/UsbDk#23]
hello.
I redirect my usb device using spice-gtk+libusb+usbdk, but it timeout, How to solve this problem?
I compile UsbDk through the newest commit in github, win10-x64 system. 
thank you！

[UsbDk.txt](https://github.com/daynix/UsbDk/files/281438/UsbDk.txt)

**Comment by jinyyu** [comment]
I have solved this problem, thanks

**Comment by dmitryfleytman** [comment]
Great! Could you please post a few words regarding what was the problem and how it was fixed?

Thanks,
Dmitry

**Comment by jinyyu** [comment]
hello
Mybe it is just incomfortable for win10-64bit.
I try to use usbdk in win10, some devies works well while some devies redirect timeout.
I find it works well in win7.
thanks

**Comment by dmitryfleytman** [comment]
Hi,

We didn't port/test UsbDk on Windows 10 yet. Please let us know if the same issue happens on pre-Win10 OS versions.

~Dmitry
