### ISSUE TITLE
usbdk redirect invalid

### ISSUE THREAD

**Issue by lixiaoming1234** [daynix/UsbDk#25]
There is an obvious bug in usbdk , when you turn usb redirection when using U disk data transfer unplug surprised, spicy.exe will be a dead stuck, with the  bug that unable to terminate the process. When I insert u disk again, usbdk been undetectable U disk, restart the computer when u disk can be detected again. This bug has always existed,untill now did not be solved. Because of the existence of this bug. It is affecting the user experience.

**Comment by dmitryfleytman** [comment]
Hello,

Thanks for your report. This problem does not reproduce on our systems.
Are you using the latest versions of UsbDk and libusb/spice-gtk patches?

If so, could you please provide us with a crash dump [1] of the system after spicy.exe stuck?

I’d also suggest to open an issue on GitHub [2] to make collaboration easier.

Thanks,
Dmitry

[1] https://github.com/daynix/UsbDk/blob/master/Documentation/CrashDumps.txt#L48
[2] https://github.com/daynix/UsbDk/issues

**Comment by goldendeng** [comment]
hello，I meet the same problem under Windows 32-bit environment，by tracking debugging, I  found in the usbredir call "libusb_close" will be two minutes occlusion, leading to spicy.exe stuck,and the "libusb_close" will call "usbdk_helper.StopRedirect",I think maybe this function lead to spicy.exe stuck.

**Comment by dmitryfleytman** [comment]
Should be resolved in v1.0.15
