### ISSUE TITLE
CWdmUsbDeviceAccess::GetDeviceDescriptor may block the system due to no return of the GET_DESCREPTOR request.

### ISSUE THREAD

**Issue by xuyongjian** [daynix/UsbDk#28]
Should we set a timeout in CIoControlIrp::SendSynchronously() function?

**Comment by dmitryfleytman** [comment]
@xuyongjian, could you please deceive scenario when this happens? What is the problematic device? What is the descriptor type? What is device state when this happens?

**Comment by xuyongjian** [comment]
I install usbdk in a virtual machine powered by qemu & kvm.
The redirected device is "HP LaserJet M1319f MFP" printer.
When happened, the code was running into "CUsbDkFilterDevice::CStrategist::SelectStrategy". And blocked when calling UsbDkWdmUsbDeviceIsHub, which will send a request as I mentioned before.

**Comment by dmitryfleytman** [comment]
Do you have any idea why this descriptor request did not return at the first place?

**Comment by xuyongjian** [comment]
Not yet~
I catched usb log  on the host PC. Every usb packet seemed to be well.
Maybe it's a problem of the vm?

**Comment by xuyongjian** [comment]
Maybe the device does not support to get descriptor many times?

**Comment by xuyongjian** [comment]
Maybe the device does not support to get descriptor many times?

**Comment by dmitryfleytman** [comment]
According to USB standards this should not happen.

**Comment by xuyongjian** [comment]
I removed the hub check, since I would not redirect a hub into the vm :)

**Comment by dmitryfleytman** [comment]
Corresponding UsbDk logic was redesigned and now it requests device descriptor only once. This should solve the problem.
