### ISSUE TITLE
UsbDk does not detect devices connected to a USB 3.0 host controller

### ISSUE THREAD

**Issue by matlo** [daynix/UsbDk#4]
This issue was reported here:
* https://forum.gimx.fr/viewtopic.php?p=7088#p7088

**Comment by ezzze** [comment]
Have you tried with the latest code in git？ As i know, uskdk v1.0.4 will not work with USB 3.0 host controller.

**Comment by dmitryfleytman** [comment]
Indeed, USB 3.0 support was added after v1.0.4 (at commit 4dbbf0c86c76e3fb4f005ca8d3806cce16e3c61b). We will release the new official version with this fix in a next few days. Until then, just build it form the latest source.
