### ISSUE TITLE
failed to install on Windows 10 and USB doesn't work

### ISSUE THREAD

**Issue by liugengdai** [daynix/UsbDk#41]
I tried to install usbdk on my windows 10 desktop. The installation was blocked and did not succeed. Now all my USB ports don't work. I cannot enter windows now. I think I should find a bluetooth or wire keyboard and mouse. :(

Do you know what happened and how to solve the problem?

**Comment by dmitryfleytman** [comment]
Hi,

You have to boot in safe mode and uninstall UsbDk.

Are you using Windows10 RS1 with secure boot enabled?

~Dmitry

**Comment by dmitryfleytman** [comment]
Most likely the same as #42

**Comment by theiman2** [comment]
How do I uninstall it in safe mode? Running the .msi again just attempts to install, not uninstall.

**Comment by dmitryfleytman** [comment]
@theiman2, either go to control panel/uninstall software are remove UsbDk Runtime Libraries or navigate with command line to c:\program files\UsbDk runtime Libraries and run "UsbDkController.exe -u"

**Comment by dmitryfleytman** [comment]
Fixed in v1.00-19

**Comment by dmitryfleytman** [comment]
Documentation for uninstallation of UsbDk after signing error may be found [here](https://github.com/daynix/UsbDk/blob/master/Documentation/Uninstallation.txt#L15).
