### ISSUE TITLE
Installing USBdk broke all my USB ports

### ISSUE THREAD

**Issue by theiman2** [daynix/UsbDk#44]
Hi,
I attempted to install USBdk and Windows returned a signing error. However, I cannot figure out how to uninstall this software, as it was not made clear how to do so.

**Comment by dmitryfleytman** [comment]
Thanks for the report, we will extend the documentation.

**Comment by dmitryfleytman** [comment]
Documentation for uninstallation of UsbDk after signing error may be found [here](https://github.com/daynix/UsbDk/blob/master/Documentation/Uninstallation.txt#L15).
