### ISSUE TITLE
"A driver without a digital signature" warning when UsbDk install on Windows 10

### ISSUE THREAD

**Issue by jik2017** [daynix/UsbDk#47]
When UsbDk install on Windows 10,  system will wairng that  "A driver without a digital signature" ,
but the UsbDk driver is really be signed.  WHQL is required?

os version: 10.0.15063

**Comment by dmitryfleytman** [comment]
Hi,

The WHQL is not required for this type of drivers.
Where do you see this warning? Could you post screenshot?

~Dmitry

**Comment by nikola-matic** [comment]
@dmitryfleytman 

Just to tag on, I'm also getting a similar (or perhaps the same) error during a Windows 10 install, using the MSI installer.

![msi_error](https://user-images.githubusercontent.com/4415530/29486826-6e9871b6-84ef-11e7-98e9-afc5be46e857.png)

In addition,  when I try running UsbDkController.exe, all I get is "UsbDk driver installation failed", so no specifics regarding the exact cause.

OS: Win 10 - Version: 1703, Build: 15063.540

**Comment by dmitryfleytman** [comment]
@nikola-matic ,
Are you using official UsbDK build or UsbDk compiled manually?
Which version of UsbDk are you using?

**Comment by nikola-matic** [comment]
@dmitryfleytman, I'm using the compiled version; where can I find the official build?

**Comment by dmitryfleytman** [comment]
Releases can be found at https://github.com/daynix/UsbDk/releases

If you compile UsbDk yourself, you need to sign it with your key.
Official releases are signed with RedHat key during build.

**Comment by nikola-matic** [comment]
@dmitryfleytman Fantastic, thanks.

**Comment by jelabarre59** [comment]
Vanilla MSWindows 7 install still sees v1.00-22 as unsigned.  This is a copy downloaded from here, not one I have built.
