### ISSUE TITLE
BSoD when printing on USB printer.

### ISSUE THREAD

**Issue by dexter125** [daynix/UsbDk#65]
Hi,

I have installed application that uses UsbDk v1.00-19. It works well, but when I try to print 2 or more copies from Word document I get BSoD. When I print 1 copy it works perfectly, but with 2 it crashes.

I'm running on Windows 7 pro SP1 x64 and have installed all updates up to August 2018. The printer I have is HP LaserJet P2015 (USB).

Funny thing is that it is hard to reproduce. It works like a charm on my friends PC. He has the same Windows and MS Office version.

I attach full memory dump.

https://www.dropbox.com/s/9b8kwzmatvoyhc5/memory_bluescreen.7z?dl=0

Thanks in advance.

**Comment by ybendito** [comment]
1.00-22 released, should fix the problem. Please reopen if needed
