### ISSUE TITLE
installation 1-21 failed on windows 10 64 pro

### ISSUE THREAD

**Issue by boistordu** [daynix/UsbDk#77]
"There is a problem with the Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor."

**Comment by YanVugenfirer** [comment]
Hello,

1. Did you run the setup as administrator?

2. Do you have secure boot enabled?

3. Can you please provide installation logs?

Thanks,
Yan.

**Comment by boistordu** [comment]
Seems okey in fact. Your installer doesn't seem to be able to uninstall old version. The uninstaller from 19 didn't say the computer needed to reboot. So after a successful reboot, your installer had manage to properly install its version.
