### ISSUE TITLE
uninstall the usbdk, mouse and keyboard get stuck

### ISSUE THREAD

**Issue by LAIhy** [daynix/UsbDk#80]
I use the release version usbdk1.0.19, I found that the mouse and keyboard will get stuck after I uninstall the usbdk1.0.19, The only way to solve this problem is to restart the computer, I also found that this problem only happened on some computers.

Is there any other way to solve this problem besides restarting the computer？

**Comment by ybendito** [comment]
Unfortunately this does not depend on usbdk. We know that sometimes the hub driver/device does not function properly and keyboard/mouse may stop working after usbdk uninstall. We're looking for solution for that but currently do not have one.
