### ISSUE TITLE
Redir usb only qemu+usbdk on the windows_7

### ISSUE THREAD

**Issue by marian3** [daynix/UsbDk#82]
Is it possible to redirect usb (ftdi usb reader) on win7? The guest is qemu-system-mipsel.
Spice can not be used:
`c:\Program Files (x86)\qemu>qemu-system-mipsel.exe -spice port=3001,disable-ticketing
qemu-system-mipsel.exe: -spice port=3001,disable-ticketing: There is no option group 'spice'
qemu-system-mipsel.exe: -spice port=3001,disable-ticketing: spice support is disabled`

**Comment by ybendito** [comment]
qemu was built without spice support, i.e. the devel packages of spice and spice protocol were not installed at time of qemu build. You need to install required devel packages and build the qemu. If you want to redirect the ftdi device on the host to VM on the same host, this is not related to UsbDk and you do not need UsbDk, you just use usb-host
